#!/usr/bin/env python
"""
generate_wares.py — Enrich resources/wares.json with transport + volume from X4 wares.xml.

Strategy:
  1. Parse libraries/wares.xml across all layers (vanilla + DLCs).
     Each <ware> with tag "economy" yields: id, transport, volume, group, tags, name_ref.
  2. Load existing resources/wares.json (generated by Mistralys x4-core — keeps label, dataSourceID).
  3. Merge: add/overwrite transport + volume on existing entries.
     New wares (present in XML but absent from wares.json) are appended with label
     resolved from the SQLite strings DB.
  4. Write updated wares.json.

Usage:
  python scripts/catalog/generate_wares.py
  python scripts/catalog/generate_wares.py --xml C:/path/to/X4-Extractions --db path/to/x4_data.db --out path/to/wares.json
"""
from __future__ import annotations

import argparse
import json
import re
import sqlite3
import xml.etree.ElementTree as ET
from pathlib import Path

DEFAULT_XML_ROOT  = Path(r"C:\DEVS\REACT\X4-Extractions\OUTPUT")
DEFAULT_DB_PATH   = Path(r"C:\React\X4SaveEditor\src-tauri\resources\x4_data.db")
DEFAULT_OUT_PATH  = Path(r"C:\React\X4SaveEditor\src-tauri\resources\wares.json")

LAYER_DLC: dict[str, str] = {
    "00_VANILLA":            "vanilla",
    "01_SPLIT_VENDETTA":     "split",
    "02_CRADLE_OF_HUMANITY": "terran",
    "03_TIDES_OF_AVARICE":   "pirate",
    "04_KINGDOM_END":        "boron",
    "05_TIMELINES":          "timelines",
    "06_HYPERION_PACK":      "mini01",
    "07_ENVOY_PACK":         "mini02",
}


def _layer_dirs(root: Path) -> list[Path]:
    return sorted(d for d in root.iterdir() if d.is_dir() and d.name[0].isdigit())


def _dlc_for_layer(layer_dir: Path) -> str:
    return LAYER_DLC.get(layer_dir.name, layer_dir.name.lower())


# ---------------------------------------------------------------------------
# String resolution (copied from generate_equipment.py)
# ---------------------------------------------------------------------------

def load_strings(db_path: Path) -> dict[tuple[int, int], str]:
    conn = sqlite3.connect(db_path)
    cur  = conn.cursor()
    cur.execute("SELECT page, string_id, text FROM strings")
    result = {(row[0], row[1]): row[2] for row in cur.fetchall()}
    conn.close()
    return result


def _finalize(text: str | None) -> str | None:
    if text is None:
        return None
    s = text.replace(r"\(", "(").replace(r"\)", ")")
    s = re.sub(r"\((?:extra\s+large|xlarge)\)XL", "XL", s, flags=re.IGNORECASE)
    s = re.sub(r"\(large\)L",   "L", s, flags=re.IGNORECASE)
    s = re.sub(r"\(medium\)M",  "M", s, flags=re.IGNORECASE)
    s = re.sub(r"\(small\)S",   "S", s, flags=re.IGNORECASE)
    return s


def resolve(ref: str | None, strings: dict, _depth: int = 0) -> str | None:
    if not ref or _depth > 4:
        return None
    if not ref.startswith("{") and not ref.startswith("("):
        return _finalize(ref)

    text = ref
    hint = None
    if text.startswith("("):
        close = text.find("){")
        if close != -1:
            hint = text[1:close]
            text = text[close + 1:]

    if "{" not in text:
        return _finalize(hint or text)

    result_parts: list[str] = []
    remaining = text
    while remaining:
        start = remaining.find("{")
        if start == -1:
            result_parts.append(remaining)
            break
        if start > 0:
            result_parts.append(remaining[:start])
        end = remaining.find("}", start)
        if end == -1:
            break
        inner     = remaining[start + 1:end]
        remaining = remaining[end + 1:]
        parts = inner.split(",")
        if len(parts) == 2:
            try:
                page, sid = int(parts[0].strip()), int(parts[1].strip())
                resolved  = strings.get((page, sid))
                if resolved:
                    result_parts.append(resolved)
                elif hint:
                    result_parts.append(hint)
            except ValueError:
                if hint:
                    result_parts.append(hint)

    return _finalize("".join(result_parts)) or hint or None


# ---------------------------------------------------------------------------
# Parse wares.xml across all layers
# ---------------------------------------------------------------------------

def extract_economy_wares(layer_dirs: list[Path]) -> dict[str, dict]:
    """
    Returns { wareID: { transport, volume, group, tags, name_ref, dataSourceID } }
    Only wares with "economy" in their tags are kept.
    Later layers overwrite earlier ones (DLC additions/overrides win).
    """
    result: dict[str, dict] = {}

    def _process(ware: ET.Element, dlc: str) -> None:
        tags_raw = ware.get("tags", "")
        if "economy" not in tags_raw.split():
            return
        ware_id = ware.get("id")
        if not ware_id:
            return
        transport = ware.get("transport")
        volume_str = ware.get("volume")
        volume = int(volume_str) if volume_str is not None else None
        group = ware.get("group")
        tags = tags_raw.split()
        name_ref = ware.get("name")
        result[ware_id] = {
            "transport":    transport,
            "volume":       volume,
            "group":        group,
            "tags":         tags,
            "name_ref":     name_ref,
            "dataSourceID": dlc,
        }

    for layer_dir in layer_dirs:
        p = layer_dir / "libraries" / "wares.xml"
        if not p.exists():
            continue
        dlc = _dlc_for_layer(layer_dir)
        tree = ET.parse(p)
        root_el = tree.getroot()

        if root_el.tag == "wares":
            for ware in root_el.iter("ware"):
                _process(ware, dlc)
        elif root_el.tag == "diff":
            for add_el in root_el.findall("add"):
                if add_el.get("sel") in ("/wares", "/wares/"):
                    for ware in add_el:
                        if ware.tag == "ware":
                            _process(ware, dlc)

    return result


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def generate(xml_root: Path, db_path: Path, out_path: Path) -> None:
    layer_dirs = _layer_dirs(xml_root)
    print(f"XML root : {xml_root}")
    print(f"Layers   : {[d.name for d in layer_dirs]}")

    print("\n[1/3] Parsing wares.xml across all layers...")
    xml_wares = extract_economy_wares(layer_dirs)
    print(f"      {len(xml_wares)} economy wares found in XML.")

    print("[2/3] Loading existing wares.json...")
    with open(out_path, encoding="utf-8") as f:
        existing: list[dict] = json.load(f)
    existing_by_id = {e["wareID"]: e for e in existing}
    print(f"      {len(existing)} entries in wares.json.")

    print("[3/3] Merging transport + volume...")
    strings = load_strings(db_path)

    updated = 0
    added = 0

    for ware_id, data in xml_wares.items():
        if ware_id in existing_by_id:
            entry = existing_by_id[ware_id]
            if data["transport"] is not None:
                entry["transport"] = data["transport"]
            if data["volume"] is not None:
                entry["volume"] = data["volume"]
            updated += 1
        else:
            label = resolve(data["name_ref"], strings) or ware_id
            new_entry: dict = {
                "wareID":       ware_id,
                "label":        label,
                "group":        data["group"] or "",
                "transport":    data["transport"],
                "volume":       data["volume"],
                "dataSourceID": data["dataSourceID"],
                "tags":         data["tags"],
            }
            existing.append(new_entry)
            existing_by_id[ware_id] = new_entry
            added += 1

    print(f"      {updated} entries updated, {added} new entries added.")

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(existing, f, ensure_ascii=False, indent=4)

    size_kb = out_path.stat().st_size / 1024
    print(f"\nWritten: {out_path}  ({size_kb:.1f} KB)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Enrich wares.json with transport + volume from X4 XML.")
    parser.add_argument("--xml", default=str(DEFAULT_XML_ROOT), help="Path to X4 extraction root")
    parser.add_argument("--db",  default=str(DEFAULT_DB_PATH),  help="Path to x4_data.db")
    parser.add_argument("--out", default=str(DEFAULT_OUT_PATH), help="Path to wares.json to update")
    args = parser.parse_args()
    generate(Path(args.xml), Path(args.db), Path(args.out))


if __name__ == "__main__":
    main()
