// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineBoost } from "./EngineBoost";
import type { EngineFwdThrust } from "./EngineFwdThrust";
import type { EngineTravelDrive } from "./EngineTravelDrive";
import type { ShipPrice } from "./ShipPrice";

export type EngineCatalogItem = { macro_id: string, name: string, basename: string | null, description: string | null, faction: string | null, size: string | null, mk: number | null, hull: number | null, boost: EngineBoost | null, travel: EngineTravelDrive | null, thrust: EngineFwdThrust | null, price: ShipPrice | null, owners: Array<string>, player_usable: boolean, };
