// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageEntry = { id: number, time: number, title: string, source: string, text: string, high_priority: boolean, };
