// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModBonus } from "./ModBonus";

export type ModStat = { ware: string, name: string | null, category: string, stat: string, quality: number, min: number, max: number, bonuses: Array<ModBonus> | null, };
