// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeployableInfo } from "./DeployableInfo";
import type { FactionRep } from "./FactionRep";
import type { InventoryItem } from "./InventoryItem";
import type { LicenceEntry } from "./LicenceEntry";
import type { NpcInfo } from "./NpcInfo";
import type { SaveSummary } from "./SaveSummary";
import type { ShipInfo } from "./ShipInfo";
import type { StationInfo } from "./StationInfo";

export type PlayerBasics = { summary: SaveSummary, inventory: Array<InventoryItem>, blueprints: Array<string>, reputations: Array<FactionRep>, ships: Array<ShipInfo>, npcs: Array<NpcInfo>, stations: Array<StationInfo>, deployables: Array<DeployableInfo>, licences: Array<LicenceEntry>, known_clusters: Array<string>, known_sectors: Array<string>, sector_owners: { [key: string]: string }, cluster_owners: { [key: string]: string }, };
