// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchEntry } from "./PatchEntry";

export type SaveSummary = { player_name: string, save_name: string, save_date: number, money: number, location: string, game_version: string, game_build: string, modified: boolean, patches: Array<PatchEntry>, };
