// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SectorCatalogItem = { macro: string, name: string, dlc: string, description: string | null, pos_x: number, pos_z: number, sunlight: number | null, economy: number | null, security: number | null, faction: string | null, resources: { [key: string]: string }, region_shape: string | null, region_r: number | null, region_linear: number | null, };
