// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShipSlot = { name: string, type: string, size: string | null, tags: Array<string>, };
