// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShipDrag } from "./ShipDrag";
import type { ShipInertia } from "./ShipInertia";

export type ShipPhysics = { mass: number | null, drag: ShipDrag | null, inertia: ShipInertia | null, accfactors: Record<string, number> | null, };
