// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StationStorageSlot = { id: string, macro_id: string, 
/**
 * `space` = stock station ; `shipconnection` = soute vaisseau amarré
 */
connection: string, };
