// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WeaponBullet = { speed: number | null, lifetime: number | null, chargetime: number | null, amount: number, barrelamount: number, icon: string | null, };
