// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShipPrice } from "./ShipPrice";
import type { WeaponBullet } from "./WeaponBullet";
import type { WeaponDamage } from "./WeaponDamage";
import type { WeaponReload } from "./WeaponReload";

export type WeaponCatalogItem = { macro_id: string, name: string, basename: string | null, description: string | null, faction: string | null, size: string | null, mk: number | null, is_turret: boolean, weapon_type: string | null, hull: number | null, bullet: WeaponBullet, damage: WeaponDamage, reload: WeaponReload, heat_value: number | null, weapon_system: string | null, range_km: number | null, dps_hull: number | null, dps_shield: number | null, price: ShipPrice | null, owners: Array<string>, player_usable: boolean, };
