// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectorCatalogItem } from "./SectorCatalogItem";

export type ClusterCatalogItem = { macro: string, name: string, dlc: string, description: string | null, grid_x: number, grid_z: number, faction: string | null, sectors: Array<SectorCatalogItem>, };
