// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeployableInfo = { class: string, macro_id: string, code: string, sector_macro: string | null, };
