// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineBoost = { duration: number | null, recharge: number | null, thrust: number | null, acceleration: number | null, attack: number | null, release: number | null, coast: number | null, };
