// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineTravelDrive = { charge: number | null, thrust: number | null, attack: number | null, release: number | null, };
