// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineCatalogItem } from "./EngineCatalogItem";
import type { ShieldCatalogItem } from "./ShieldCatalogItem";
import type { ThrusterCatalogItem } from "./ThrusterCatalogItem";
import type { WeaponCatalogItem } from "./WeaponCatalogItem";

export type EquipmentCatalog = { weapons: Array<WeaponCatalogItem>, engines: Array<EngineCatalogItem>, shields: Array<ShieldCatalogItem>, thrusters: Array<ThrusterCatalogItem>, };
