// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InventoryCatalogItem = { id: string, name: string, group_id: string | null, tags: string | null, price: number | null, };
