// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModBonus = { stat: string, min: number, max: number, chance: number, max_count: number, };
