// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NpcInfo = { name: string, code: string, id: string, race: string, role: string, post: string, piloting: number, management: number, morale: number, engineering: number, boarding: number, ship_code: string | null, ship_name: string | null, station_code: string | null, station_name: string | null, };
