// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResearchMaterial } from "./ResearchMaterial";

export type ResearchEntry = { id: string, name: string | null, description: string | null, time: number, sortorder: number | null, hidden: boolean, missiononly: boolean, nocustomgamestart: boolean, dlc: string, prerequisites: Array<string>, materials: Array<ResearchMaterial>, };
