// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClusterCatalogItem } from "./ClusterCatalogItem";

export type SectorsCatalog = { clusters: Array<ClusterCatalogItem>, };
