// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShieldRecharge } from "./ShieldRecharge";
import type { ShipPrice } from "./ShipPrice";

export type ShieldCatalogItem = { macro_id: string, name: string, basename: string | null, description: string | null, faction: string | null, size: string | null, mk: number | null, hull: number | null, recharge: ShieldRecharge | null, price: ShipPrice | null, owners: Array<string>, player_usable: boolean, };
