// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShipDrag = { forward: number | null, reverse: number | null, horizontal: number | null, vertical: number | null, pitch: number | null, yaw: number | null, roll: number | null, };
