// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormationInfo } from "./FormationInfo";
import type { ShipMod } from "./ShipMod";

export type ShipInfo = { macro_id: string, name: string | null, id: string, code: string, class: string, size: string, faction: string, hull: string, hull_type: string | null, is_docked: boolean, sector_macro: string | null, 
/**
 * Dernier cluster (macro sans suffixe _macro) dans la pile géo au moment du ship
 */
cluster_macro: string | null, 
/**
 * Dernière zone dans la pile géo, si le vaisseau y est rattaché
 */
zone_macro: string | null, 
/**
 * Attribut XML `state` (ex. normal, wreck)
 */
state: string, crew_count: number, shields: Array<string>, weapons: Array<string>, turrets: Array<string>, engines: Array<string>, software: Array<string>, thruster: string | null, current_order: string | null, formation: FormationInfo | null, wingman_leader: string | null, fleet_name: string | null, mods: Array<ShipMod>, };
