// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShipCargo } from "./ShipCargo";
import type { ShipPhysics } from "./ShipPhysics";
import type { ShipPrice } from "./ShipPrice";
import type { ShipSlot } from "./ShipSlot";
import type { ShipSoftware } from "./ShipSoftware";

export type ShipCatalogItem = { macro_id: string, name: string, basename: string, description: string | null, size: string | null, ship_type: string | null, faction: string | null, variation: string | null, icon: string | null, hull: number | null, people_capacity: number | null, storage: Record<string, number>, cargo: ShipCargo | null, radar_range: number | null, physics: ShipPhysics | null, thruster_tags: Array<string>, software: Array<ShipSoftware>, slots: Array<ShipSlot>, slot_counts: Record<string, number>, price: ShipPrice | null, owners: Array<string>, player_usable: boolean, hangar_storage: Record<string, number>, docking_pads: Record<string, number>, };
