// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationStorageSlot } from "./StationStorageSlot";
import type { WareAmount } from "./WareAmount";

export type StationInfo = { macro_id: string, name: string | null, code: string, kind: string, faction: string, sector_macro: string | null, modules: Array<string>, cargo: Array<WareAmount>, storage_slots: Array<StationStorageSlot>, };
