// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShipPrice } from "./ShipPrice";
import type { ThrusterAngular } from "./ThrusterAngular";
import type { ThrusterThrust } from "./ThrusterThrust";

export type ThrusterCatalogItem = { macro_id: string, name: string, basename: string | null, description: string | null, faction: string | null, size: string | null, mk: number | null, thrust: ThrusterThrust | null, angular: ThrusterAngular | null, price: ShipPrice | null, owners: Array<string>, player_usable: boolean, };
